name: HTML CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Setup SSH & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SSH_HOST: ssh.serversandgen.web.id
          SSH_USER: ${{ secrets.USERNAME }}
        run: |
          # 1. Setup kunci SSH agar bisa digunakan oleh sistem
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 2. Skip host key verification (agar tidak muncul prompt yes/no)
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

          # 3. Jalankan SSH dengan ProxyCommand Cloudflared
          ssh -i ~/.ssh/id_rsa -o "ProxyCommand=cloudflared access ssh --hostname $SSH_HOST" $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/html/templateProject
            git pull origin main
            git status
          EOF
